version: '2'

services:
  app:
    container_name: app
    build: .
    environment:
      - APP_PORT=8080
      - ELASTIC_SEARCH_URL=http:elasticsearch
      - ELASTIC_SEARCH_PORT=9200
      - ELASTIC_SEARCH_VERSION=7
    command: npm start
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl --silent --fail localhost:9200/_cluster/health || exit 1',
        ]
      interval: 30s
      timeout: 30s
      retries: 6

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  elasticsearch:
    driver: local
